version: "3.3"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "dev"
      # You can use whatever password you like
      MYSQL_PASSWORD: "dev"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "dev"
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "4040:3306"
    volumes:
      - sequelize:/var/lib/mysql

  adminer:
    image: "adminer"
    ports:
      - "5050:8080"
    environment:
      ADMINER_DESIGN: pepa-linha

volumes:
  sequelize:
